from __future__ import annotations
#!/usr/bin/env python3

""" mininet/label_window.py  Post-Run Attack Labeler 
This script adds labels to SDN flow data captured from the Mininet runs.
After running program with attacks, this tool will mark the flows,
during the attack window, as malicious (label=1).
Usage:
python3 mininet/label_window.py --file data/live_client1.csv \
  --start "2026-05-18T14:30:00" --end "2026-05-18T14:35:00"
or for convienence, label everything since my whole capture is an attack:
python3 mininet/label_window.py --file data/attack_only.csv --all --label 1
"""

import argparse
import pandas as pd
import sys

# Label flows within a specific time window or label all rows
def label_window(file: str, start: str | None, end: str | None,
                 label: int, label_all: bool):
    # Add attack labels to flows based on timestamp or label everything
    print(f"[Label] Loading file: {file}")
    df = pd.read_csv(file)

    # Check for required timestamp column
    if "timestamp" not in df.columns:
        print(f"[!] Error: 'timestamp' column not found in {file}")
        print("    Make sure this CSV was generated by ryu_collector.py")
        sys.exit(1)

    # Add label column if it doesn't exist
    if "label" not in df.columns:
        df["label"] = 0
        print("[Label] Added new 'label' column (default = 0)")

    # Convert timestamp to proper datetime format
    df["timestamp"] = pd.to_datetime(df["timestamp"], format="ISO8601")

    if label_all:
        # Label every single row
        mask = pd.Series([True] * len(df))
        print(f"[Label] Labeling ALL {len(df):,} rows as label={label}")
    else:
        # Label only flows within the given time window
        if not start or not end:
            print("[!] Error: You must provide --start and --end, or use --all")
            sys.exit(1)
        
        t_start = pd.to_datetime(start)
        t_end = pd.to_datetime(end)
        
        mask = (df["timestamp"] >= t_start) & (df["timestamp"] <= t_end)
        n_match = mask.sum()
        
        print(f"[Label] Time window: {start} -> {end}")
        print(f"[Label] Matched {n_match:,} rows out of {len(df):,}")

    # Apply the label
    df.loc[mask, "label"] = label

    # Save back to the same file
    df.to_csv(file, index=False)
    
    print(f"\n[Label] Successfully saved updated file: {file}")
    print(f"[Label] Final label distribution:")
    print(df['label'].value_counts().to_string())
    print()


if __name__ == "__main__":
    # Create and configure the command-line parser, including all
    # supported commands and their options.  
    parser = argparse.ArgumentParser(
        description="Label attack flows in live-captured SDN CSV files by time window",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument("--file", required=True, 
                       help="Path to the live capture CSV file")
    parser.add_argument("--start", default=None, 
                       help="Start time (ISO format: YYYY-MM-DDTHH:MM:SS)")
    parser.add_argument("--end", default=None, 
                       help="End time (ISO format: YYYY-MM-DDTHH:MM:SS)")
    parser.add_argument("--label", type=int, default=1, 
                       help="Label value to assign (0=benign, 1=attack)")
    parser.add_argument("--all", action="store_true",
                       help="Label every row in the file (use for pure attack captures)")
    
    args = parser.parse_args()
    label_window(args.file, args.start, args.end, args.label, args.all)
